version: '3.3'
services:
  bind:
    image: davinbao/bind:latest
    deploy:
      replicas: 1
      endpoint_mode: vip
      resources:
        limits:
          memory: 512M
    volumes:
    - /xmisp/docker/bind/conf:/etc/bind:rw
    - /root/.ssh:/root/.ssh:ro
    - /etc/ssh:/etc/ssh:ro
    ports:
    - 53:53/udp
    - 2222:22
    environment:
      INTERVAL: 10s
    networks:
      - backend