version: '3.3'
services:
  bind:
    image: davinbao/bind:latest
    deploy:
      replicas: 1
      endpoint_mode: vip
      resources:
        limits:
          memory: 512M
    volumes:
    - /xmisp/docker/bind/conf:/etc/bind
    - /xmisp/docker/rsync/conf:/etc/monitor
    ports:
    - 53:53/udp
    networks:
      - backend